languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://resume.io"
title = "Gabriel Rodriguez Resume"
googleAnalytics = "Resume"

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#212834"
colorPrimary = "#048BC2"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#048BC2"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#048BC2"
pages = 1
